export const OBTER_PROJETOS = "OBTER_PROJETOS"
export const CRIAR_PROJETO = "CRIAR_PROJETO"
export const EDITAR_PROJETO = "EDITAR_PROJETO"
export const APAGAR_PROJETO = "APAGAR_PROJETO"

export const OBTER_TAREFAS = "OBTER_TAREFAS"
export const CRIAR_TAREFA = "CRIAR_TAREFA"
export const EDITAR_TAREFA = "EDITAR_TAREFA"
export const APAGAR_TAREFA = "APAGAR_TAREFA"